### PR TITLE
Update SDK to 21.08

### PR DESCRIPTION
**Pull request by gasinvein**

### CODE REVIEW

**Comment by nanonyme** [comment]
Looks good to me.

**Comment by gasinvein** [comment]
Nah, it's broken:
```
Traceback (most recent call last):
  File "/app/bin/flatpak-external-data-checker", line 28, in <module>
    from src.main import main  # noqa: E402
  File "/app/lib/fedc/src/main.py", line 36, in <module>
    from github import Github
  File "/app/lib/python3.9/site-packages/github/__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "/app/lib/python3.9/site-packages/github/MainClass.py", line 59, in <module>
    import github.Event
  File "/app/lib/python3.9/site-packages/github/Event.py", line 32, in <module>
    import github.NamedUser
  File "/app/lib/python3.9/site-packages/github/NamedUser.py", line 44, in <module>
    import github.Organization
  File "/app/lib/python3.9/site-packages/github/Organization.py", line 50, in <module>
    import github.Repository
  File "/app/lib/python3.9/site-packages/github/Repository.py", line 125, in <module>
    import github.PublicKey
  File "/app/lib/python3.9/site-packages/github/PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "/app/lib/python3.9/site-packages/nacl/public.py", line 17, in <module>
    import nacl.bindings
  File "/app/lib/python3.9/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_aead import (
  File "/app/lib/python3.9/site-packages/nacl/bindings/crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named 'nacl._sodium'
```

**Comment by nanonyme** [comment]
Has to break earlier, right? PyNaCL didn't somehow build correctly.

**Comment by nanonyme** [comment]
Eeee, so PyNaCL built but doesn't work?

**Comment by gasinvein** [comment]
> Eeee, so PyNaCL built but doesn't work?

Yeah :-/

**Comment by gasinvein** [comment]
Manually built PyNaCl seems to work fine. I wonder what is wrong with pip-driven build.

**Comment by nanonyme** [comment]
I don't know but I guess we have until Python 3.12 to find out.

**Comment by gasinvein** [comment]
Oh well. I guess PyNaCl and libsodium are a security-sensitive libraries, so it makes sense to auto-update them anyway.

**Pull request merged**
